#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 08, 2021 10:40:31 PM -03  platform: Linux

from tkinter.constants import END
from persistencia import anotacao
import os
import base64
import codecs
import PyPDF2
import tkdocviewer
from tkinter import filedialog

try:
    import Tkinter as tk # type: ignore
except ImportError:
    import tkinter as tk

try:
    import ttk # type: ignore
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

class Toplevel6:
    def __init__(self, id, matricula, caderno, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        self.id = id
        self.matricula = matricula
        self.caderno = caderno

        self.top = tk.Tk()
        self.top.geometry("600x512+660+210")
        self.top.minsize(1, 1)
        self.top.maxsize(1905, 1050)
        self.top.resizable(1,  1)
        self.top.title("New Toplevel")
        self.top.configure(background="#F2E7C4")

        anotacoes = anotacao(self.matricula, self.caderno)
        anotacao_selecionada = anotacoes.anotacao_especifica(id)

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.083, rely=0.313, relheight=0.455, relwidth=0.843)

        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {gothic} -size 15")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")
        self.Text1.insert(END, anotacao_selecionada[3])

        self.Button1 = tk.Button(self.top, command=lambda: self.atualiza_anotacao(anotacoes))
        self.Button1.place(relx=0.583, rely=0.111, height=47, width=82)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(text='''Salvar''')

        self.Button1 = tk.Button(self.top, command=lambda: self.apagar_anotacao(anotacoes))
        self.Button1.place(relx=0.79, rely=0.111, height=47, width=82)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(text='''Apagar''')


        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.083, rely=0.133, height=37, relwidth=0.377)
        self.Entry1.configure(background="white")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.insert(END, anotacao_selecionada[2])

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.067, rely=0.059, height=29, width=79)
        self.Label1.configure(background="#F2E7C4")
        self.Label1.configure(font="-family {gothic} -size 20")
        self.Label1.configure(text='''Nome''')

        self.Button2 = tk.Button(self.top,command=lambda: self.insere_pdf(anotacoes))
        self.Button2.place(relx=0.583, rely=0.859, height=37, width=122)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(text='''Inserir PDF''')

        self.Button2_1 = tk.Button(self.top, command=lambda: self.abre_pdf(anotacoes))
        self.Button2_1.place(relx=0.217, rely=0.859, height=37, width=122)
        self.Button2_1.configure(activebackground="#f9f9f9")
        self.Button2_1.configure(borderwidth="2")
        self.Button2_1.configure(text='''Visualizar PDF''')

        self.top.mainloop()

    def atualiza_anotacao(self, anotacoes):
        anotacoes.edita_anotacao(self.id, self.Entry1.get(), self.Text1.get("1.0",END))

    def apagar_anotacao(self, anotacoes):
        anotacoes.apaga_anotacao(self.id)
        self.top.destroy()
    
    def insere_pdf(self, anotacoes):
        
        currdir = os.getcwd()

        FILEOPENOPTIONS = dict(defaultextension=".pdf", initialdir="/home/",
                       filetypes=[('pdf file', '*.pdf')])

        caminho_pdf = filedialog.askopenfilename(**FILEOPENOPTIONS)

        if len(caminho_pdf) > 0:
            anotacoes.insere_pdf(self.id, caminho_pdf)
            self.top.destroy()
            Toplevel6(self.id, self.matricula, self.caderno)

    def abre_pdf(self, anotacoes):
        #binario = anotacoes.visualiza_pdf(self.id)
        
        #with open(os.path.expanduser('/home/joao/Área de Trabalho/test.pdf'), 'wb') as fout:
        #    fout.write(base64.decodebytes(codecs.encode(binario, 'base64')))

        janela = tk.Toplevel()
        janela.geometry("700x700+660+210")

        v = tkdocviewer.DocViewer(janela)
        v.pack(side="top", expand=1, fill="both")

        # Display this README file
        v.display_file("/home/joao/Área de Trabalho/test.pdf")
  

