#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 08, 2021 10:40:31 PM -03  platform: Linux

from tkinter.constants import END
from persistencia import anotacao

import sys

try:
    import Tkinter as tk # type: ignore
except ImportError:
    import tkinter as tk

try:
    import ttk # type: ignore
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


class Toplevel5:
    def __init__(self, matricula, caderno, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        self.matricula = matricula
        self.caderno = caderno

        self.top = tk.Tk()
        self.top.geometry("600x512+660+210")
        self.top.minsize(1, 1)
        self.top.maxsize(1905, 1050)
        self.top.resizable(1,  1)
        self.top.title("New Toplevel")
        self.top.configure(background="#F2E7C4")

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.083, rely=0.313, relheight=0.455, relwidth=0.843)

        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {gothic} -size 15")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Button1 = tk.Button(self.top, command=self.salva_nova_anotacao)
        self.Button1.place(relx=0.74, rely=0.111, height=47, width=82)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(text='''Salvar''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.083, rely=0.133, height=37, relwidth=0.377)
        self.Entry1.configure(background="white")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure()

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.067, rely=0.059, height=29, width=79)
        self.Label1.configure(background="#F2E7C4")
        self.Label1.configure(font="-family {gothic} -size 20")
        self.Label1.configure(text='''Nome''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.583, rely=0.859, height=37, width=122)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(text='''Inserir PDF''')

        self.Button2_1 = tk.Button(self.top)
        self.Button2_1.place(relx=0.217, rely=0.859, height=37, width=122)
        self.Button2_1.configure(activebackground="#f9f9f9")
        self.Button2_1.configure(borderwidth="2")
        self.Button2_1.configure(text='''Visualizar PDF''')

        self.top.mainloop()

    def salva_nova_anotacao(self):
        nova_anotacao = anotacao(self.matricula, self.caderno)
        nova_anotacao.cria_anotacao(self.Entry1.get(), self.Text1.get("1.0",END))
        self.top.destroy()
