#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 08, 2021 04:42:28 PM -03  platform: Linux

import sys
from tkinter import Toplevel
from tkinter.constants import ANCHOR, END, FIRST

try:
    import Tkinter as tk # type: ignore
except ImportError:
    import tkinter as tk

try:
    import ttk # type: ignore 
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from persistencia import *
from novoCaderno import *
from anotacoes import *

class Toplevel2:
    def __init__(self, matricula, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#F2E7C4'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#F2E7C4' # X11 color: 'gray85'
        _ana1color = '#F2E7C4' # X11 color: 'gray85'
        _ana2color = '#F2E7C4' # Closest X11 color: 'gray92'

        self.matricula = matricula

        self.top = tk.Tk()
        self.top.geometry("813x470+574+198")
        self.top.minsize(1, 1)
        self.top.maxsize(1905, 1050)
        self.top.resizable(1,  1)
        self.top.title("New Toplevel")
        self.top.configure(background='#F2E7C4')

        self.Listbox1 = tk.Listbox(self.top)
        self.Listbox1.place(relx=0.16, rely=0.234, relheight=0.56
                , relwidth=0.673)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="-family {gothic} -size 15")

        cadernos = caderno(self.matricula)
        meus_cadernos = cadernos.meus_cadernos()
        lista_cadernos = [item[0] + " - " + item[1] for item in meus_cadernos]
        
        if len(lista_cadernos) == 0:
            self.Listbox1.insert(END, "Você ainda não possui cadernos")

        for item in lista_cadernos:
            self.Listbox1.insert(END, item)
            self.Listbox1.configure(foreground='#205459')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.098, rely=0.085, height=57, width=283)
        self.Label1.configure(font="-family {gothic} -size 20")
        self.Label1.configure(text='''Meus Cadernos''', background="#F2E7C4", foreground='#205459')

        self.Button1 = tk.Button(self.top, command=self.criar_caderno)
        self.Button1.place(relx=0.16, rely=0.851, height=57, width=132)
        self.Button1.configure(borderwidth="2", background="#F25757", foreground='white')
        self.Button1.configure(text='''Criar novo''')

        self.Button2 = tk.Button(self.top, command=self.consulta_status) 
        self.Button2.place(relx=0.4, rely=0.851, height=57, width=132) 
        self.Button2.configure(borderwidth="2", background="#F25757", foreground='white')
        self.Button2.configure(text='''Status''')

        self.Button2 = tk.Button(self.top, command=lambda: self.acessar_caderno(meus_cadernos)) 
        self.Button2.place(relx=0.677, rely=0.851, height=57, width=132) 
        self.Button2.configure(borderwidth="2", background="#F25757", foreground='white')
        self.Button2.configure(text='''Acessar''')

        self.Button3 = tk.Button(self.top, command=self.atualiza) 
        self.Button3.place(relx=0.677, rely=0.1, height=57, width=132) 
        self.Button3.configure(borderwidth="2", background="#F28F38", foreground='white')
        self.Button3.configure(text='''Atualizar''')

        self.Button4 = tk.Button(self.top, command=self.melhores_cadernos) 
        self.Button4.place(relx=0.5, rely=0.1, height=57, width=132) 
        self.Button4.configure(borderwidth="2", background="#F28F38", foreground='white')
        self.Button4.configure(text='''Melhores Cadernos''')

        self.top.mainloop()

    def criar_caderno(self):
        Toplevel3(self.matricula)


    def atualiza(self):
        self.top.destroy()
        Toplevel2(self.matricula)

    def acessar_caderno(self, meus_cadernos):
        nome_caderno = meus_cadernos[self.Listbox1.index(ANCHOR)][0]
        Toplevel4(self.matricula, nome_caderno)
    
    def melhores_cadernos(self):
        cadernos = melhores_cadernos().consultar_melhores()
        lista_cadernos = [item[0] + " - " + item[2] + " - " + str(item[3]) for item in cadernos]
        janela = tk.Toplevel()
        janela.geometry("700x400+660+210")
        
        Listboxt = tk.Listbox(janela)
        Listboxt.place(relx=0.16, rely=0.234, relheight=0.56
                , relwidth=0.673)
        Listboxt.configure(background="white")
        Listboxt.configure(font="-family {gothic} -size 15")

        if len(cadernos) == 0:
            Listboxt.insert(END, "Você ainda não possui cadernos")
        
        for item in lista_cadernos:
            Listboxt.insert(END, item)
            Listboxt.configure(foreground='#205459')

        print(lista_cadernos)

    def consulta_status(self):
        status = destaques().status(self.matricula)
        janela2 = tk.Toplevel()
        janela2.geometry("400x400+660+210")
        Label_Status = tk.Label(janela2)
        Label_Status.place(relx=0.098, rely=0.085, height=57, width=283)
        Label_Status.configure(font="-family {gothic} -size 20")
        Label_Status.configure(text=status, background="#F2E7C4", foreground='#205459')


        

        





