#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 07, 2021 09:41:00 PM -03  platform: Linux

import sys

try:
    import Tkinter as tk # type: ignore
except ImportError:
    import tkinter as tk

try:
    import ttk # type: ignore
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from persistencia import *
from meusCadernos import *

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        self.top = tk.Tk()
        self.top.geometry("813x470+574+198")
        self.top.minsize(1, 1)
        self.top.maxsize(1905, 1050)
        self.top.resizable(1,  1)
        self.top.title("New Toplevel")
        self.top.configure(background="#037F8C")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        self.top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.295, rely=0.149, relheight=0.691
                , relwidth=0.426)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#F2E7C4")
        self.Frame1.configure(cursor="fleur")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.318, rely=0.031, height=55, width=109)
        self.Label1.configure(background="#F2E7C4")
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(font="-family {gothic} -size 20")
        self.Label1.configure(foreground="#205459")
        self.Label1.configure(text='''Login''')

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.145, rely=0.369, height=37, relwidth=0.74)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Entry2 = tk.Entry(self.Frame1, show='*')
        self.Entry2.place(relx=0.145, rely=0.677, height=37, relwidth=0.74)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(selectbackground="blue")
        self.Entry2.configure(selectforeground="white")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.145, rely=0.243, height=36, width=119)
        self.Label2.configure(background="#F2E7C4")
        self.Label2.configure(font="-family {gothic} -size 15")
        self.Label2.configure(foreground="#205459")
        self.Label2.configure(text='''Matrícula''')

        self.Label2_1 = tk.Label(self.Frame1)
        self.Label2_1.place(relx=0.116, rely=0.542, height=44, width=89)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(background="#F2E7C4")
        self.Label2_1.configure(cursor="fleur")
        self.Label2_1.configure(font="-family {gothic} -size 15")
        self.Label2_1.configure(foreground="#205459")
        self.Label2_1.configure(text='''Senha''')

        self.Button1 = tk.Button(self.Frame1, command=self.verificaCadastro)
        self.Button1.place(relx=0.376, rely=0.862, height=37, width=92)
        self.Button1.configure(background="#F25757")
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(cursor="fleur")
        self.Button1.configure(font="-family {gothic} -size 9")
        self.Button1.configure(foreground="#F2E7C4")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Entrar''')
        self.top.mainloop()

    def verificaCadastro(self):
        a = aluno(self.Entry1.get())

        if a.confere_login(self.Entry2.get()):
            print("Usuario logado")
            self.top.destroy()
            Toplevel2(a.matricula)
        else:
            print('Dados incorretos')



Toplevel1()





